---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.5.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: false
    download: true
    fetch: true
    git: true
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: The jsonnet-bundler is a package manager for Jsonnet.
app_name: jb
app_repo: https://github.com/jsonnet-bundler/jsonnet-bundler
app_type: standalone
app_website: https://github.com/jsonnet-bundler/jsonnet-bundler/
archive_enabled: false
checksum_enabled: false
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v{version}/jb-{os}-{arch}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    jb: bin/jb
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-jsonnet-bundler
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-jsonnet-bundler.git
source_enabled: true
source_type: git
source_url: https://github.com/jsonnet-bundler/jsonnet-bundler.git
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    i386: amd64
    i686: amd64
    powerpc64le: amd64
    ppc64le: amd64
    x86: amd64
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
